# Generated by Django 2.2.4 on 2019-08-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20190808_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song'),
        ),
    ]
